name: Hubzilla Container CI

on: push

jobs:
  build:
    if: |
      !contains(fromJson('["refs/heads/dev"]'), github.ref)
    runs-on: ubuntu-latest
    steps:
    - id:   checkout
      name: Checkout
      uses: actions/checkout@v4.1.1
    - id:   dotenv
      name: Dotenv
      uses: falti/dotenv-action@v1.1
    - id:   qemu_setup
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - id:   buildx_setup
      name: Setup Buildx
      uses: docker/setup-buildx-action@v3.1.0
    - id:   dckrhub_login
      name: DockerHub Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id:   build_push
      name: Build the Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        push: true
        tags: |
          dhitchenor/hubzilla:latest
          dhitchenor/hubzilla:${{ steps.dotenv.outputs.ver_full }}
          dhitchenor/hubzilla:${{ steps.dotenv.outputs.ver_major }}
